apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: { { include "nodeporter.fullname" . } }
  labels: { { - include "nodeporter.labels" . | nindent 4 } }
rules:
  - apiGroups: ['']
    resources: ['services', 'nodes']
    verbs: ['get', 'list', 'watch']
