# Default values for nodeporter Helm chart.
replicaCount: 1

image:
  repository: ghcr.io/kopernic-pl/nodeporter-dashboard
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
