name: Build and Push Docker image to GHCR

on:
  push:
    tags:
      - 'release/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tag version
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_ENV
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build and push Docker image (multi-platform)
        run: |
          chmod +x ./ops/build_and_dockerize.sh
          ./ops/build_and_dockerize.sh ${{ env.TAG }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/nodeporter-dashboard:${{ env.TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/nodeporter-dashboard:latest
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release/${{ env.TAG }}
          name: Release ${{ env.TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}